name: VueJS CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy VueJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            npm install --global yarn
            cd PWA-App
            git stash
            git pull origin master
            yarn install
            yarn run build
